/* AUTO-GENERATED by combine.py on startup. Do not edit by hand. */
(function() {
  var _lip = '10.10.42.180';
  var _hn  = (window.location && window.location.hostname) || '';
  var _useHost = (window.location.protocol !== 'file:') &&
                 (_hn === _lip || _hn === 'localhost' || _hn === '127.0.0.1');
  var _h = _useHost ? (window.location.protocol + '//' + _hn) : 'http://' + _lip;
  window.APP_CONFIG = {
    LAPTOP_IP: "10.10.42.180",
    FLASK_PORT: 5000,
    ATTENDANCE_PORT: 5001,
    STUDENTS_BASE_URL: _h + ':5000',
    EMAIL_BASE_URL: _h + ':5001',
    QUIZ_URL: _h + ':5000/get_quiz',
    GENERATED_AT: "2026-05-20 19:24:27"
  };
})();
