# -*- coding: utf-8 -*-

import json
import os
import smtplib
import socket
import traceback
import threading
import base64
import uuid
import io
import time
import qrcode

from datetime import datetime
from http.server import BaseHTTPRequestHandler, HTTPServer
from email.message import EmailMessage
from urllib.parse import urlparse, parse_qs

import mysql.connector
from openpyxl import Workbook

from flask import Flask, request, jsonify, render_template_string, send_from_directory
from PIL import Image
from google import genai


# =========================================================
# MERGED EMAIL CONFIG
# =========================================================
EMAIL_SENDER = "pepperclass2026@gmail.com"
EMAIL_APP_PASSWORD = "dybv tied zwfh uilx"
EMAIL_RECEIVER = "mariaekanaan@gmail.com"


# =========================================================
# DATABASE CONFIG
# =========================================================
DB_CONFIG = {
    "host": "localhost",
    "port": 3303,
    "user": "root",
    "password": "",
    "database": "classroom_db"
}

HOST = "0.0.0.0"

# Flask app will stay on 5000
FLASK_PORT = 5000

# Attendance HTTPServer moved to 5001 to avoid conflict
ATTENDANCE_PORT = 5001

ADMIN_PASSWORD = "admin123"


# =========================================================
# GEMINI / FLASK CONFIG
# =========================================================
api_key = "AIzaSyCOnzhHk7I60BDaI2No53vDjMRUCcEDPO4"
client = genai.Client(api_key=api_key)

MODEL_NAME = "gemini-2.5-flash-image"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
STATIC_DIR = os.path.join(BASE_DIR, "static")
HTML_DIR = os.path.join(BASE_DIR, "html")
HTML_JS_DIR = os.path.join(HTML_DIR, "js")
HTML_DATA_DIR = os.path.join(HTML_DIR, "data")
TRANSLATIONS_DIR = os.path.join(BASE_DIR, "translations")
GEMINI_LOG_PATH = os.path.join(BASE_DIR, "gemini_logs.txt")

for folder in [UPLOAD_DIR, STATIC_DIR, HTML_JS_DIR]:
    if not os.path.exists(folder):
        os.makedirs(folder)


# =========================================================
# AUTO-DETECT LAPTOP IP (no more manual edits!)
# =========================================================
def detect_local_ip():
    """
    Returns the LAN IP this machine uses to reach the outside world.
    Tries a UDP "connect" trick (no packets actually sent), then falls
    back to hostname resolution, then to 127.0.0.1.
    """
    ip = None
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.connect(("8.8.8.8", 80))
            ip = s.getsockname()[0]
        finally:
            s.close()
    except Exception:
        ip = None

    if not ip or ip.startswith("127."):
        try:
            ip = socket.gethostbyname(socket.gethostname())
        except Exception:
            ip = None

    if not ip or ip.startswith("127."):
        ip = "127.0.0.1"

    return ip


LAPTOP_IP = os.environ.get("LAPTOP_IP") or detect_local_ip()


def write_frontend_config():
    """
    Writes html/js/config.js so every front-end page picks up the current
    laptop IP without anyone editing HTML. Pepper-safe ES5, no fetch, no
    arrow functions, no template literals.
    """
    config_path = os.path.join(HTML_JS_DIR, "config.js")
    payload = (
        "/* AUTO-GENERATED by combine.py on startup. Do not edit by hand. */\n"
        "(function() {{\n"
        "  var _lip = '{ip}';\n"
        "  var _hn  = (window.location && window.location.hostname) || '';\n"
        "  var _useHost = (window.location.protocol !== 'file:') &&\n"
        "                 (_hn === _lip || _hn === 'localhost' || _hn === '127.0.0.1');\n"
        "  var _h = _useHost ? (window.location.protocol + '//' + _hn) : 'http://' + _lip;\n"
        "  window.APP_CONFIG = {{\n"
        "    LAPTOP_IP: \"{ip}\",\n"
        "    FLASK_PORT: {flask_port},\n"
        "    ATTENDANCE_PORT: {att_port},\n"
        "    STUDENTS_BASE_URL: _h + ':{flask_port}',\n"
        "    EMAIL_BASE_URL: _h + ':{att_port}',\n"
        "    QUIZ_URL: _h + ':{flask_port}/get_quiz',\n"
        "    GENERATED_AT: \"{ts}\"\n"
        "  }};\n"
        "}})();\n"
    ).format(
        ip=LAPTOP_IP,
        flask_port=5000,
        att_port=5001,
        ts=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(payload)
        print("[CONFIG] Wrote {} (LAPTOP_IP={})".format(config_path, LAPTOP_IP))
    except Exception as e:
        print("[CONFIG] Failed to write config.js: {}".format(e))

    # Also drop a plain-text IP file for Pepper-side (NAOqi Python 2) boxes
    # in translations/behavior.xar to read on load.
    ip_txt_paths = [
        os.path.join(TRANSLATIONS_DIR, "laptop_ip.txt"),
        os.path.join(BASE_DIR, "laptop_ip.txt"),
    ]
    for p in ip_txt_paths:
        try:
            d = os.path.dirname(p)
            if d and not os.path.exists(d):
                os.makedirs(d)
            with open(p, "w") as f:
                f.write(LAPTOP_IP)
            print("[CONFIG] Wrote {}".format(p))
        except Exception as e:
            print("[CONFIG] Failed to write {}: {}".format(p, e))


def log_gemini(message):
    """Append a timestamped message to gemini_logs.txt"""
    try:
        with open(GEMINI_LOG_PATH, "a", encoding="utf-8") as f:
            f.write("[{}] {}\n".format(datetime.now(), message))
    except Exception:
        pass

INPUT_PATH = os.path.join(UPLOAD_DIR, "pepper_input.jpg")

app = Flask(__name__, static_folder=STATIC_DIR, static_url_path="/static")

# stores the current tablet selection
LATEST_RESULT_URL = "" 
LATEST_QR_URL = ""
CURRENT_CHOICE = None

PROMPTS = {
    "sunglasses": (
        "Edit this photo to add stylish photorealistic sunglasses to every visible person in the image. "
        "Apply the sunglasses to all people detected in the photo, not just one person. "
        "Preserve each person's identity, face, hairstyle, expression, pose, clothing, and the original background. "
        "Make each pair of sunglasses realistic, naturally aligned to the eyes, and correctly matched in size, angle, lighting, and perspective for each individual."
    ),
    "hat": (
        "Edit this photo to add a photorealistic stylish hat to every visible person in the image. "
        "Apply the hat to all people detected in the photo, not just one person. "
        "Preserve each person's identity, face, hairstyle as much as possible, expression, pose, clothing, and the original background. "
        "Make each hat fit naturally on each head with correct scale, angle, lighting, shadows, and perspective."
    ),
    "funny_hair": (
        "Edit this photo to add photorealistic funny hair styling to every visible person in the image. "
        "Apply the funny hair effect to all people detected in the photo, not just one person. "
        "Preserve each person's identity, face, expression, pose, clothing, and the original background. "
        "Make the hair playful but realistic, well blended, and naturally aligned to each head with correct scale, angle, lighting, and perspective."
    ),
    "cartoon": (
        "Transform every visible person in this photo into a high-quality cartoon style version. "
        "Apply the cartoon effect to all people in the image, not just one person. "
        "Preserve each person's identity, facial features, hairstyle, expression, pose, clothing, and the original composition. "
        "Keep the background recognizable and clean. "
        "Make the result look like a polished colorful cartoon portrait, smooth, fun, and visually appealing."
    ),
}

CHOICE_HTML = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Pepper Photobooth</title>

<style>
body{
    margin:0;
    font-family:Arial, sans-serif;
    height:100vh;
    background:url("/static/background.png") center center/cover no-repeat;
    display:flex;
    justify-content:center;
    align-items:center;
}

.overlay{
    background:rgba(0,0,0,0.45);
    width:100%;
    height:100%;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
}

h1{
    color:white;
    font-size:44px;
    margin-bottom:50px;
    text-shadow:0 4px 10px rgba(0,0,0,0.6);
}

.container{
    display:grid;
    grid-template-columns:repeat(2, 220px);
    gap:25px 35px;
    justify-content:center;
}

button{
    width:220px;
    height:110px;
    font-size:24px;
    font-weight:bold;
    border:none;
    border-radius:25px;
    cursor:pointer;
    color:black;
    backdrop-filter:blur(8px);
    background:rgba(255,255,255,0.9);
    box-shadow:0 10px 25px rgba(0,0,0,0.4);
    transition:all 0.25s ease;
}

button:hover{
    transform:scale(1.08);
    background:rgba(255,255,255,0.95);
}

#msg{
    margin-top:40px;
    font-size:28px;
    font-weight:bold;
    color:white;
}
</style>
</head>

<body>
<div class="overlay">
    <h1>Pick a Style 😎</h1>

    <div class="container">
        <button onclick="sendChoice('sunglasses')">😎 Sunglasses</button>
        <button onclick="sendChoice('hat')">🎩 Hat</button>
        <button onclick="sendChoice('funny_hair')">😂 Funny Hair</button>
        <button onclick="sendChoice('cartoon')">🎨 Cartoon</button>
    </div>

    <div id="msg"></div>
</div>

<script>
function sendChoice(choice){
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/set_choice", true);
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");

    xhr.onreadystatechange = function(){
        if(xhr.readyState === 4){
            if(xhr.status === 200){
                document.getElementById("msg").innerHTML = "Applying " + choice + "...";
            } else {
                document.getElementById("msg").innerHTML = "Connection error";
            }
        }
    };

    xhr.send(JSON.stringify({choice: choice}));
}
</script>
</body>
</html>
"""

RESULT_OPTIONS_HTML = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Next Step</title>

<style>
body{
    margin:0;
    font-family:Arial, sans-serif;
    height:100vh;
    background:url("/static/background.png") center center/cover no-repeat;
    display:flex;
    justify-content:center;
    align-items:center;
}

.overlay{
    background:rgba(0,0,0,0.45);
    width:100%;
    height:100%;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
}

h1{
    color:white;
    font-size:42px;
    margin-bottom:20px;
    text-shadow:0 4px 10px rgba(0,0,0,0.6);
}

.qr-box {
    background: rgba(255, 255, 255, 0.95);
    padding: 20px;
    border-radius: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 30px;
    box-shadow: 0 10px 25px rgba(0,0,0,0.5);
}

.qr-box p {
    margin: 0 0 15px 0;
    font-size: 24px;
    font-weight: bold;
    color: #333;
}

.qr-box img {
    width: 200px;
    height: 200px;
    border-radius: 10px;
}

.container{
    display:flex;
    flex-direction:row; /* Puts buttons side by side */
    gap:25px;
    justify-content:center;
}

button{
    width:220px;
    height:90px;
    font-size:26px;
    font-weight:bold;
    border:none;
    border-radius:25px;
    cursor:pointer;
    color:black;
    backdrop-filter:blur(8px);
    background:rgba(255,255,255,0.9);
    box-shadow:0 10px 25px rgba(0,0,0,0.4);
    transition:all 0.25s ease;
}

button:hover{
    transform:scale(1.05);
    background:rgba(255,255,255,0.95);
}
</style>
</head>

<body>
<div class="overlay">
    <h1>What would you like to do?</h1>

    <div class="qr-box">
        <p>📸 Scan to download!</p>
        <img src="{{ qr_url }}" alt="QR Code" />
    </div>

    <div class="container">
        <button onclick="sendChoice('retry')">🔄 Try Again</button>
        <button onclick="sendChoice('next')">➡ Next</button>
    </div>
</div>

<script>
function sendChoice(choice){
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/set_choice", true);
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xhr.send(JSON.stringify({choice: choice}));
}
</script>
</body>
</html>
"""

LOADING_HTML = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Creating Image</title>

<style>
body{
    margin:0;
    font-family:Arial, sans-serif;
    height:100vh;
    background:url("/static/background.png") center center/cover no-repeat;
    display:flex;
    justify-content:center;
    align-items:center;
    overflow:hidden;
}

.overlay{
    background:rgba(0,0,0,0.55);
    width:100%;
    height:100%;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
}

.loader{
    width:110px;
    height:110px;
    border:10px solid rgba(255,255,255,0.25);
    border-top:10px solid white;
    border-radius:50%;
    animation:spin 1s linear infinite;
    margin-bottom:35px;
}

h1{
    color:white;
    font-size:42px;
    margin:0 0 18px 0;
    text-shadow:0 4px 10px rgba(0,0,0,0.6);
}

p{
    color:white;
    font-size:26px;
    margin:0;
    text-shadow:0 4px 10px rgba(0,0,0,0.6);
}

#dots::after{
    content:"";
    animation:dots 1.5s steps(4,end) infinite;
}

@keyframes spin{
    from{transform:rotate(0deg);}
    to{transform:rotate(360deg);}
}

@keyframes dots{
    0%{content:"";}
    25%{content:".";}
    50%{content:"..";}
    75%{content:"...";}
    100%{content:"";}
}
</style>
</head>

<body>
<div class="overlay">
    <div class="loader"></div>
    <h1>Creating your picture</h1>
    <p>Please wait<span id="dots"></span></p>

    <audio id="waitingAudio" autoplay loop>
        <source src="/static/waiting_music.mp3" type="audio/mpeg">
    </audio>
</div>

<script>
window.onload = function(){
    var audio = document.getElementById("waitingAudio");
    if(audio){
        var playPromise = audio.play();
        if(playPromise !== undefined){
            playPromise.catch(function(e){
                console.log("Autoplay blocked:", e);
            });
        }
    }
};
</script>
</body>
</html>
"""


# =========================================================
# ATTENDANCE SERVER FUNCTIONS
# =========================================================
def get_db_connection():
    print("[DB] Attempting connection to MySQL: host={}, user={}, database={}".format(
        DB_CONFIG['host'], DB_CONFIG['user'], DB_CONFIG['database']))
    try:
        conn = mysql.connector.connect(**DB_CONFIG)
        print("[DB] Connection successful! Server version: {}".format(conn.get_server_info()))
        return conn
    except Exception as e:
        print("[DB] CONNECTION FAILED: {}: {}".format(type(e).__name__, str(e)))
        raise


def get_present_students():
    print("[DB] get_present_students() called")
    conn = get_db_connection()
    cursor = conn.cursor()

    # First check what tables exist
    try:
        cursor.execute("SHOW TABLES")
        tables = cursor.fetchall()
        print("[DB] Tables in '{}': {}".format(DB_CONFIG['database'], [t[0] for t in tables]))
    except Exception as e:
        print("[DB] SHOW TABLES failed: {}".format(str(e)))

    # Check table structure
    try:
        cursor.execute("DESCRIBE attendance")
        columns = cursor.fetchall()
        print("[DB] 'attendance' columns: {}".format([(c[0], c[1]) for c in columns]))
    except Exception as e:
        print("[DB] DESCRIBE attendance failed: {}".format(str(e)))

    # Count all rows
    try:
        cursor.execute("SELECT COUNT(*) FROM attendance")
        total = cursor.fetchone()[0]
        print("[DB] Total rows in attendance: {}".format(total))
    except Exception as e:
        print("[DB] COUNT(*) failed: {}".format(str(e)))

    # Show sample rows
    try:
        cursor.execute("SELECT * FROM attendance LIMIT 5")
        sample = cursor.fetchall()
        print("[DB] Sample rows (up to 5): {}".format(sample))
    except Exception as e:
        print("[DB] Sample query failed: {}".format(str(e)))

    cursor.execute("""
        SELECT DISTINCT student_name
        FROM attendance
        WHERE student_name IS NOT NULL
          AND TRIM(student_name) <> ''
        ORDER BY student_name ASC
    """)

    results = cursor.fetchall()
    students = [row[0] for row in results]
    print("[DB] Found {} distinct students: {}".format(len(students), students))

    cursor.close()
    conn.close()

    return students


def create_attendance_excel(students):
    wb = Workbook()
    ws = wb.active
    ws.title = "Attendance"

    ws["A1"] = "Present Students"
    ws["B1"] = "Generated At"

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    for index, student in enumerate(students, start=2):
        ws["A{}".format(index)] = student
        ws["B{}".format(index)] = now_str

    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 24

    file_name = "attendance_{}.xlsx".format(
        datetime.now().strftime("%Y%m%d_%H%M%S")
    )
    file_path = os.path.join(os.getcwd(), file_name)
    wb.save(file_path)

    return file_path, file_name


def send_email_with_attachment(file_path, file_name, students_count):
    try:
        msg = EmailMessage()
        msg["Subject"] = "Attendance Report"
        msg["From"] = EMAIL_SENDER
        msg["To"] = EMAIL_RECEIVER

        msg.set_content(
            "Hello,\n\n"
            "Please find attached the attendance Excel sheet.\n"
            "Number of present students: {}\n\n"
            "Best regards.".format(students_count)
        )

        with open(file_path, "rb") as f:
            file_data = f.read()

        msg.add_attachment(
            file_data,
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            filename=file_name
        )

        print("Connecting to Gmail SMTP...")
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as smtp:
            smtp.set_debuglevel(1)
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()

            print("Logging in as:", EMAIL_SENDER)
            smtp.login(EMAIL_SENDER, EMAIL_APP_PASSWORD)

            print("Sending email to:", EMAIL_RECEIVER)
            smtp.send_message(msg)

        print("Email sent successfully.")

    except Exception as e:
        print("EMAIL ERROR:", str(e))
        traceback.print_exc()
        raise


class MyHandler(BaseHTTPRequestHandler):

    def send_json_response(self, data, status_code=200):
        response = json.dumps(data).encode("utf-8")

        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(response)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        self.wfile.write(response)

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        try:
            parsed_url = urlparse(self.path)
            path = parsed_url.path
            params = parse_qs(parsed_url.query)

            if path == "/students":
                students_list = get_present_students()
                self.send_json_response({
                    "success": True,
                    "students": students_list
                })

            elif path == "/send_attendance_email":
                password = params.get("password", [""])[0]

                if password != ADMIN_PASSWORD:
                    self.send_json_response({
                        "success": False,
                        "error": "Incorrect password"
                    }, 401)
                    return

                students_list = get_present_students()

                if not students_list:
                    self.send_json_response({
                        "success": False,
                        "error": "No students found in database"
                    }, 400)
                    return

                file_path, file_name = create_attendance_excel(students_list)
                send_email_with_attachment(file_path, file_name, len(students_list))

                self.send_json_response({
                    "success": True,
                    "message": "Attendance email sent successfully to {}".format(
                        EMAIL_RECEIVER
                    )
                })

            else:
                self.send_json_response({
                    "success": False,
                    "error": "Route not found"
                }, 404)

        except Exception as e:
            traceback.print_exc()
            self.send_json_response({
                "success": False,
                "error": str(e)
            }, 500)

    def log_message(self, format, *args):
        print("%s - - [%s] %s" % (
            self.client_address[0],
            self.log_date_time_string(),
            format % args
        ))


def run_attendance_server():
    server = HTTPServer((HOST, ATTENDANCE_PORT), MyHandler)
    print("Attendance server running on http://{}:{}".format(HOST, ATTENDANCE_PORT))
    server.serve_forever()


# =========================================================
# FLASK / GEMINI FUNCTIONS
# =========================================================
def save_returned_image(response, output_path):
    if getattr(response, "candidates", None):
        for candidate in response.candidates:
            content = getattr(candidate, "content", None)
            if not content:
                continue
            parts = getattr(content, "parts", None) or []
            for part in parts:
                inline_data = getattr(part, "inline_data", None)
                if inline_data and getattr(inline_data, "data", None):
                    with open(output_path, "wb") as f:
                        f.write(inline_data.data)
                    return True

    if getattr(response, "parts", None):
        for part in response.parts:
            inline_data = getattr(part, "inline_data", None)
            if inline_data and getattr(inline_data, "data", None):
                with open(output_path, "wb") as f:
                    f.write(inline_data.data)
                return True

    return False


@app.route("/html/<path:filename>")
def serve_html(filename):
    return send_from_directory(HTML_DIR, filename)


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"ok": True, "model": MODEL_NAME})


@app.route("/choice", methods=["GET"])
def choice_page():
    return render_template_string(CHOICE_HTML)


@app.route("/result_options", methods=["GET"])
def result_options():
    global LATEST_QR_URL
    # Passes the global QR url into the {{ qr_url }} slot in the HTML
    return render_template_string(RESULT_OPTIONS_HTML, qr_url=LATEST_QR_URL)


@app.route("/loading", methods=["GET"])
def loading_page():
    return render_template_string(LOADING_HTML)


@app.route("/set_choice", methods=["POST"])
def set_choice():
    global CURRENT_CHOICE
    try:
        data = request.get_json(force=True)
        choice = data.get("choice", "").strip().lower()

        valid_choices = list(PROMPTS.keys()) + ["retry", "next"]
        if choice not in valid_choices:
            return jsonify({"ok": False, "error": "Invalid choice"}), 400

        CURRENT_CHOICE = choice
        return jsonify({"ok": True, "choice": CURRENT_CHOICE})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500


@app.route("/get_choice", methods=["GET"])
def get_choice():
    global CURRENT_CHOICE
    return jsonify({
        "ok": True,
        "choice": CURRENT_CHOICE
    })


@app.route("/reset_choice", methods=["POST"])
def reset_choice():
    global CURRENT_CHOICE
    CURRENT_CHOICE = None
    return jsonify({"ok": True})


@app.route("/students", methods=["GET", "OPTIONS"])
def flask_students():
    print("[FLASK] /students endpoint hit, method={}".format(request.method))
    if request.method == "OPTIONS":
        response = jsonify({"success": True})
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "GET, OPTIONS"
        response.headers["Access-Control-Allow-Headers"] = "Content-Type"
        return response

    try:
        students_list = get_present_students()
        print("[FLASK] Returning {} students".format(len(students_list)))
        response = jsonify({
            "success": True,
            "students": students_list
        })
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "GET, OPTIONS"
        response.headers["Access-Control-Allow-Headers"] = "Content-Type"
        return response
    except Exception as e:
        response = jsonify({
            "success": False,
            "error": str(e)
        })
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "GET, OPTIONS"
        response.headers["Access-Control-Allow-Headers"] = "Content-Type"
        return response, 500


@app.route("/edit_json", methods=["POST"])
def edit_json():
    try:
        data = request.get_json(force=True)

        choice = data.get("choice", "sunglasses").strip().lower()
        image_b64 = data.get("image_b64", "")

        if choice not in PROMPTS:
            return jsonify({"ok": False, "error": "Invalid choice"}), 400

        if not image_b64:
            return jsonify({"ok": False, "error": "No image_b64 provided"}), 400

        prompt = PROMPTS[choice]
        image_bytes = base64.b64decode(image_b64)

        with open(INPUT_PATH, "wb") as f:
            f.write(image_bytes)

        img = Image.open(INPUT_PATH)

        # Retry logic for transient 503 errors
        max_retries = 3
        response = None
        for attempt in range(1, max_retries + 1):
            try:
                log_gemini("REQUEST [attempt {}/{}] model={} choice={}".format(attempt, max_retries, MODEL_NAME, choice))
                response = client.models.generate_content(
                    model=MODEL_NAME,
                    contents=[prompt, img]
                )
                log_gemini("RESPONSE OK [attempt {}] candidates={}".format(
                    attempt, len(response.candidates) if getattr(response, 'candidates', None) else 0))
                break
            except Exception as api_err:
                log_gemini("ERROR [attempt {}/{}] {}: {}".format(attempt, max_retries, type(api_err).__name__, str(api_err)))
                if attempt < max_retries:
                    time.sleep(2 * attempt)  # exponential backoff
                else:
                    log_gemini("FAILED all {} retries for choice={}".format(max_retries, choice))
                    return jsonify({"ok": False, "error": "Gemini API error after {} retries: {}".format(max_retries, str(api_err))}), 503

        filename = "result_" + str(uuid.uuid4()) + ".png"
        output_path = os.path.join(STATIC_DIR, filename)

        ok = save_returned_image(response, output_path)
        if not ok:
            log_gemini("NO IMAGE in response for choice={}".format(choice))
            return jsonify({"ok": False, "error": "Gemini returned no image output"}), 500

        # UPDATE STARTS HERE
        global LATEST_RESULT_URL, LATEST_QR_URL
        
        result_url = "http://%s:%s/static/%s" % (LAPTOP_IP, FLASK_PORT, filename)
        LATEST_RESULT_URL = result_url

        # 1. Generate the QR Code linked to the result_url
        qr_image = qrcode.make(result_url)
        
        # 2. Save the QR Code to the static folder
        qr_filename = "qr_" + filename
        qr_output_path = os.path.join(STATIC_DIR, qr_filename)
        qr_image.save(qr_output_path)
        
        # 3. Create the URL for the QR code
        LATEST_QR_URL = "http://%s:%s/static/%s" % (LAPTOP_IP, FLASK_PORT, qr_filename)

        log_gemini("SUCCESS choice={} result_url={}".format(choice, result_url))

        return jsonify({
            "ok": True,
            "choice": choice,
            "result_url": result_url,
            "qr_url": LATEST_QR_URL # Pass this back just in case your frontend script needs it
        })
    except Exception as e:
        log_gemini("UNHANDLED ERROR: {}: {}".format(type(e).__name__, str(e)))
        return jsonify({"ok": False, "error": str(e)}), 500
    
@app.route('/get_quiz', methods=['GET'])
def get_quiz():
    # Resolve relative to this file so it works on any machine / path.
    json_path = os.path.join(HTML_DATA_DIR, "questions.json")
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            questions = json.load(f)
        response = jsonify(questions)
        response.headers["Access-Control-Allow-Origin"] = "*"
        return response
    except Exception as e:
        response = jsonify({"error": str(e)})
        response.headers["Access-Control-Allow-Origin"] = "*"
        return response, 500


# =========================================================
# RUN BOTH SERVERS
# =========================================================
if __name__ == "__main__":
    # Refresh front-end config.js with the current laptop IP every time
    # the server starts. No more editing IPs in HTML files.
    write_frontend_config()

    print("=" * 60)
    print(" LAPTOP_IP detected : {}".format(LAPTOP_IP))
    print(" Students API       : http://{}:{}/students".format(LAPTOP_IP, FLASK_PORT))
    print(" Email API          : http://{}:{}/send_attendance_email".format(LAPTOP_IP, ATTENDANCE_PORT))
    print(" Override with env  : LAPTOP_IP=x.x.x.x python combine.py")
    print("=" * 60)

    attendance_thread = threading.Thread(target=run_attendance_server, daemon=True)
    attendance_thread.start()

    print("Flask app running on http://{}:{}".format(HOST, FLASK_PORT))
    app.run(host=HOST, port=FLASK_PORT, debug=True, use_reloader=False)